name: Publish Docker image
on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - '!.github/workflows/docker.yml'
      - .vscode/**
      - .gitignore
      - LICENSE
      - README.md

  workflow_dispatch:

jobs:
  dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: spencer0003/matrixwebhooks

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: spencer0003/matrixwebhooks:latest
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Publish to Github
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/spencer-0003/matrixwebhooks:latest
          labels: ${{ steps.metadata.outputs.labels }}